FROM php:7.4-fpm-buster

RUN apt-get update && apt-get install -y


RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
    && docker-php-ext-install \
           zip \
           intl \
           mysqli \
           pdo pdo_mysql


RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY checkout51/ /var/www/checkout51
WORKDIR /var/www/checkout51
CMD composer install ; wait-for-it mysql:3306 -- bin/console doctrine:migrations:migrate ;  php-fpm
EXPOSE 9000
