<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMqU7Jqc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMqU7Jqc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMqU7Jqc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMqU7Jqc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMqU7Jqc\App_KernelDevDebugContainer([
    'container.build_hash' => 'MqU7Jqc',
    'container.build_id' => 'ae98c8cd',
    'container.build_time' => 1598844304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMqU7Jqc');
