<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIS1LPcf\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIS1LPcf/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerIS1LPcf.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerIS1LPcf\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerIS1LPcf\App_KernelTestDebugContainer([
    'container.build_hash' => 'IS1LPcf',
    'container.build_id' => 'baa26fac',
    'container.build_time' => 1598842769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIS1LPcf');
