<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'offers' => [[], ['_controller' => 'App\\Controller\\OfferController::index'], [], [['text', '/offers']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\OfferController::index'], [], [['text', '/']], [], []],
];
