<?php

namespace Container0IPLjql;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_OfferServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'app.offer_service' shared autowired service.
     *
     * @return \App\Service\OfferService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/OfferService.php';

        return $container->privates['app.offer_service'] = new \App\Service\OfferService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
